create table produtos (
    id bigint generated by default as identity,
    descricao varchar(255),
    nome varchar(255),
    preco float(53),
    primary key (id)
);

insert into produtos (nome, descricao, preco) values ('Notebook Dell', 'Notebook 15" com 16GB RAM', 4999.90);
insert into produtos (nome, descricao, preco) values ('Smartphone Galaxy', 'Smartphone Samsung Galaxy S22', 3599.00);
insert into produtos (nome, descricao, preco) values ('Monitor LG', 'Monitor LED 24" Full HD', 899.99);
insert into produtos (nome, descricao, preco) values ('Teclado Mecânico', 'Teclado gamer com iluminação RGB', 279.50);
insert into produtos (nome, descricao, preco) values ('Mouse Logitech', 'Mouse sem fio ergonômico', 199.90);
insert into produtos (nome, descricao, preco) values ('Cadeira Gamer', 'Cadeira ergonômica com apoio lombar', 1299.00);
insert into produtos (nome, descricao, preco) values ('Webcam HD', 'Webcam 1080p com microfone', 349.99);
insert into produtos (nome, descricao, preco) values ('Headset', 'Fone com microfone para jogos', 439.00);
insert into produtos (nome, descricao, preco) values ('HD Externo', 'Disco rígido externo 1TB USB 3.0', 329.99);
insert into produtos (nome, descricao, preco) values ('Impressora Wi-Fi', 'Impressora multifuncional com conexão sem fio', 699.00);
